# Custom Language File for Launcher Customizer

[ejs.app]
title = "Poime SMP Chapter 2 Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/PoimeYT/Poime-SMP-Chapter-2-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/PoimeYT/Poime-SMP-Chapter-2-Launcher"
supportLink = "https://github.com/PoimeYT/Poime-SMP-Chapter-2-Launcher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO A NEW CHAPTER"
welcomeDescription = "Welcome to POIME SMP CHAPTER 2 (not copied from fortnite def trust)."
welcomeDescCTA = "You are just a few clicks away from joining."
